# Generated by Django 3.1.4 on 2021-01-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To'),
        ),
    ]
