# Generated by Django 3.1.4 on 2021-01-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210104_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profile'),
        ),
    ]
