# Generated by Django 3.1.4 on 2021-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_info_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='bio',
            field=models.TextField(max_length=512, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='info',
            name='interests',
            field=models.TextField(max_length=512, verbose_name='Interests'),
        ),
    ]
